resolver: lts-7.12
packages:
- servant-client-static-header/
- servant-server-static-header/
- servant-static-header/
extra-deps: 
- http-api-data-0.3.3
- servant-0.9.1.1
- servant-client-0.9.1.1
- servant-server-0.9.1.1
flags: {}
